### ISSUE TITLE
Sapper: SyntaxError: Unexpected token '<' leads to server crash

### ISSUE THREAD

**Issue by riccardolardi** [kaisermann/svelte-loadable#36]
In Sapper: whenever I `import Loadable from 'svelte-loadable';` I get the following server crash:

```
/Users/riccardolardi/Code/studioriccardolardi_sapper/node_modules/svelte-loadable/Loadable.svelte:1
<script context="module">
^

SyntaxError: Unexpected token '<'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/riccardolardi/Code/studioriccardolardi_sapper/__sapper__/dev/server/server.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
> Server crashed
```

**Comment by x4080** [comment]
Confirm that using svelte template, when I'm using elderjs template it works

**Comment by riccardolardi** [comment]
Yes using svelte template

**Comment by x4080** [comment]
I mean i got the same experience with svelte template, do you have solution for it?

**Comment by kaisermann** [comment]
Hey, @riccardolardi 👋  Can you share a repro?

**Comment by riccardolardi** [comment]
@kaisermann sorry I ended up loading the component dynamically using a async/await: https://github.com/riccardolardi/studioriccardolardi/blob/master/src/components/ClientModule.svelte

Therefore I've left the approach using `svelte-loadable`...
